dyc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: material_database
    username: root
    password: 1234
  mongodb:
    host: localhost
    port: 27017
    database: picture