server:
  port: 8083
spring:
  application:
    name: SCUMaterial
  profiles:
    active: dev
  datasource:
    type: ${dyc.datasource.type}
    driver-class-name: ${dyc.datasource.driver-class-name}
    url: jdbc:mysql://${dyc.datasource.host}:${dyc.datasource.port}/${dyc.datasource.database}
    username: ${dyc.datasource.username}
    password: ${dyc.datasource.password}
  data:
    mongodb:
      uri: mongodb://${dyc.mongodb.host}:${dyc.mongodb.port}/${dyc.mongodb.database}
      # 实验室的mongodb
#      uri: mongodb://${sys.mongodb.username}:${sys.mongodb.password}@${sys.mongodb.host}:${sys.mongodb.port}/${sys.mongodb.database}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mappers/**/*.xml

#mybatis:
#  mapper-locations:
#  configuration:
#    map-underscore-to-camel-case: true
#mybatis.mapperloca