dyc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: material_database
    username: root
    password: 1234
  mongodb:
    uri: mongodb://username:password@host:port/database
    database: picture
    host: 192.168.26.72
    port: 27017